import streamlit as st

from utils.html import render_html


PROJECT_SECTIONS = [
    {
        "title": "Problem Statement",
        "label": "Why SPIRE exists",
        "body": (
            "Many people know exercise is beneficial, but struggle to maintain routines "
            "because progress can feel abstract, lonely, or disconnected from immediate "
            "meaning. SPIRE addresses motivation, adherence, and perceived impact by "
            "turning exercise completion into visible personal and community progress."
        ),
    },
    {
        "title": "Solution",
        "label": "Game companion approach",
        "body": (
            "SPIRE is a fantasy-inspired exercise companion app. Users complete exercise "
            "quests, build streaks, unlock achievements, connect with friends, and generate "
            "Hope Energy. The interface is designed to make health behavior feel like a "
            "cooperative journey rather than a checklist."
        ),
    },
    {
        "title": "Technology Stack",
        "label": "Prototype implementation",
        "body": (
            "The current demonstrator is built with Python and Streamlit, using modular "
            "multipage views, mock data, custom HTML/CSS components, and service/data "
            "folders prepared for future separation of interface and application logic."
        ),
    },
    {
        "title": "Physiotherapist Validation",
        "label": "Clinical grounding",
        "body": (
            "The concept should be validated with physiotherapists to ensure exercise "
            "guidance, progression, reminders, and motivational framing are safe, realistic, "
            "and appropriate for the intended user group. Future versions could include "
            "clinician-reviewed exercise libraries and adaptive difficulty."
        ),
    },
    {
        "title": "Charity Integration Concept",
        "label": "Hope Energy model",
        "body": (
            "Hope Energy is a non-monetary community score generated by exercise completion. "
            "In a future deployment, sponsors or institutional partners could pledge donations "
            "when transparent milestones are reached, allowing healthy actions to contribute "
            "to charitable initiatives without asking users to donate directly."
        ),
    },
    {
        "title": "Future Vision",
        "label": "Where SPIRE could go",
        "body": (
            "SPIRE could evolve into a validated social health platform with personalized "
            "exercise plans, therapist dashboards, stronger community challenges, sponsor "
            "campaign management, accessibility features, and real-world impact reporting."
        ),
    },
]

TECH_ITEMS = [
    "Python",
    "Streamlit",
    "Custom CSS",
    "Mock data layer",
    "Multipage app structure",
    "Future service modules",
]


def _inject_about_css():
    render_html(
        """
        <style>
            :root {
                --spire-purple: #7C3AED;
                --spire-dark: #1A1A1A;
                --spire-light: #E5E5E5;
                --spire-border: rgba(229, 229, 229, 0.13);
                --spire-muted: rgba(229, 229, 229, 0.68);
            }

            .stApp {
                background:
                    radial-gradient(circle at 12% 0%, rgba(124, 58, 237, 0.22), transparent 30rem),
                    radial-gradient(circle at 86% 12%, rgba(229, 229, 229, 0.08), transparent 22rem),
                    var(--spire-dark);
                color: var(--spire-light);
            }

            [data-testid="stHeader"] {
                background: transparent;
            }

            .block-container {
                max-width: 1180px;
                padding-top: 2rem;
                padding-bottom: 3rem;
            }

            .about-shell {
                color: var(--spire-light);
                font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            }

            .about-hero {
                border: 1px solid rgba(124, 58, 237, 0.38);
                border-radius: 8px;
                padding: 1.65rem;
                background:
                    linear-gradient(110deg, rgba(26, 26, 26, 0.97), rgba(35, 33, 41, 0.88)),
                    url("https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80");
                background-position: center;
                background-size: cover;
                box-shadow: 0 22px 70px rgba(0, 0, 0, 0.36);
            }

            .eyebrow {
                color: var(--spire-purple);
                font-size: 0.78rem;
                font-weight: 850;
                letter-spacing: 0.12em;
                text-transform: uppercase;
            }

            .about-hero h1 {
                max-width: 820px;
                margin: 0.35rem 0 0;
                color: #FFFFFF;
                font-size: clamp(2.1rem, 5vw, 4.15rem);
                font-weight: 900;
                line-height: 0.98;
                letter-spacing: 0;
            }

            .hero-copy,
            .section-body,
            .meta-copy,
            .vision-copy {
                color: var(--spire-muted);
                line-height: 1.6;
            }

            .hero-copy {
                max-width: 810px;
                margin: 0.85rem 0 0;
                font-size: 1.03rem;
            }

            .summary-grid {
                display: grid;
                grid-template-columns: repeat(3, minmax(0, 1fr));
                gap: 0.9rem;
                margin-top: 1rem;
            }

            .summary-card,
            .section-card,
            .stack-card,
            .vision-card {
                border: 1px solid var(--spire-border);
                border-radius: 8px;
                background: linear-gradient(145deg, rgba(45, 41, 54, 0.96), rgba(26, 26, 26, 0.96));
                box-shadow: 0 16px 36px rgba(0, 0, 0, 0.28);
            }

            .summary-card,
            .section-card,
            .stack-card,
            .vision-card {
                padding: 1rem;
            }

            .summary-value {
                margin-top: 0.65rem;
                color: #FFFFFF;
                font-size: 1.85rem;
                font-weight: 900;
                line-height: 1;
            }

            .section-title {
                margin: 1.55rem 0 0.8rem;
                color: #FFFFFF;
                font-size: 1rem;
                font-weight: 850;
                letter-spacing: 0.08em;
                text-transform: uppercase;
            }

            .content-grid {
                display: grid;
                grid-template-columns: repeat(2, minmax(0, 1fr));
                gap: 0.9rem;
            }

            .section-card {
                min-height: 210px;
                position: relative;
                overflow: hidden;
            }

            .section-card::before {
                content: "";
                position: absolute;
                inset: 0;
                border-top: 2px solid rgba(124, 58, 237, 0.7);
                pointer-events: none;
            }

            .section-label {
                color: var(--spire-purple);
                font-size: 0.75rem;
                font-weight: 850;
                letter-spacing: 0.1em;
                text-transform: uppercase;
            }

            .section-heading {
                margin-top: 0.55rem;
                color: #FFFFFF;
                font-size: 1.28rem;
                font-weight: 900;
                line-height: 1.2;
            }

            .section-body {
                margin-top: 0.65rem;
            }

            .bottom-grid {
                display: grid;
                grid-template-columns: minmax(0, 0.8fr) minmax(0, 1.2fr);
                gap: 0.9rem;
                margin-top: 1rem;
            }

            .tech-list {
                display: flex;
                flex-wrap: wrap;
                gap: 0.55rem;
                margin-top: 0.85rem;
            }

            .tech-pill {
                border: 1px solid rgba(124, 58, 237, 0.52);
                border-radius: 999px;
                padding: 0.32rem 0.72rem;
                background: rgba(124, 58, 237, 0.16);
                color: #D8C8FF;
                font-size: 0.78rem;
                font-weight: 800;
            }

            .vision-steps {
                display: grid;
                gap: 0.75rem;
                margin-top: 0.85rem;
            }

            .vision-step {
                border-left: 2px solid rgba(124, 58, 237, 0.78);
                padding-left: 0.85rem;
                color: var(--spire-muted);
                line-height: 1.5;
            }

            .vision-step strong {
                color: #FFFFFF;
            }

            @media (max-width: 900px) {
                .summary-grid,
                .content-grid,
                .bottom-grid {
                    grid-template-columns: 1fr;
                }
            }
        </style>
        """,
    )


def _project_section_card(section):
    label = section["label"]
    title = section["title"]
    body = section["body"]

    return f"""
        <article class="section-card">
            <div class="section-label">{label}</div>
            <div class="section-heading">{title}</div>
            <div class="section-body">{body}</div>
        </article>
    """


def show_about():
    _inject_about_css()

    section_cards = "".join(_project_section_card(section) for section in PROJECT_SECTIONS)
    tech_pills = "".join(f'<span class="tech-pill">{item}</span>' for item in TECH_ITEMS)

    render_html(
        f"""
        <main class="about-shell">
            <section class="about-hero">
                <div class="eyebrow">About SPIRE // University Demonstrator</div>
                <h1>A gamified exercise companion for motivation, community, and impact.</h1>
                <p class="hero-copy">
                    SPIRE explores how gameful design can support exercise adherence while
                    connecting personal progress to social value. This prototype demonstrates
                    the core experience, interaction model, and future validation direction.
                </p>
            </section>

            <section class="summary-grid" aria-label="Project summary">
                <article class="summary-card">
                    <div class="eyebrow">Domain</div>
                    <div class="summary-value">Health behavior</div>
                    <div class="meta-copy">Exercise adherence through motivational design.</div>
                </article>
                <article class="summary-card">
                    <div class="eyebrow">Audience</div>
                    <div class="summary-value">Students</div>
                    <div class="meta-copy">Designed for demonstration, feedback, and assessment.</div>
                </article>
                <article class="summary-card">
                    <div class="eyebrow">Prototype</div>
                    <div class="summary-value">Streamlit app</div>
                    <div class="meta-copy">A functional interface with mock data and styled views.</div>
                </article>
            </section>

            <div class="section-title">Project Explanation</div>
            <section class="content-grid">
                {section_cards}
            </section>

            <section class="bottom-grid">
                <article class="stack-card">
                    <div class="section-label">Implementation overview</div>
                    <div class="section-heading">Technology Stack</div>
                    <div class="meta-copy">
                        The prototype prioritizes fast iteration and clear presentation over
                        production infrastructure. The structure can later be extended with
                        persistent storage, authentication, exercise validation, and analytics.
                    </div>
                    <div class="tech-list">
                        {tech_pills}
                    </div>
                </article>

                <article class="vision-card">
                    <div class="section-label">Next development steps</div>
                    <div class="section-heading">Future Vision</div>
                    <div class="vision-copy">
                        SPIRE could become a validated companion platform that links exercise,
                        professional guidance, social accountability, and responsible impact partnerships.
                    </div>
                    <div class="vision-steps">
                        <div class="vision-step"><strong>Validate:</strong> review exercise content and progression with physiotherapists.</div>
                        <div class="vision-step"><strong>Personalize:</strong> adapt quests to user ability, goals, and recovery needs.</div>
                        <div class="vision-step"><strong>Measure:</strong> evaluate motivation, adherence, usability, and perceived meaning.</div>
                        <div class="vision-step"><strong>Partner:</strong> test transparent charity campaigns with clear sponsor rules and limits.</div>
                    </div>
                </article>
            </section>
        </main>
        """,
    )


show_about()
